version: '3.8'

services:
  node: 
    container_name: node_server_boilerplate
    build:
      context: .
      dockerfile: ./DockerFile
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    command: > 
      bash -c "npm install && npm run start"
    networks:
      - api-network

networks:
  api-network:
     driver: bridge
