version: '3.8'

services:
  node: 
    container_name: node_server_boilerplate
    build:
      context: .
      dockerfile: ./.docker/api.DockerFile
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      ENV: ${ENV}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      FIREBASE_ADMIN_CONFIG: ${FIREBASE_ADMIN_CONFIG}
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./back_end:/app
    command: > 
      bash -c "npm install && npm run start"
    networks:
      - api-network
  
  front_end:
    container_name: front_end_boilerplate
    build:
      context: .
      dockerfile: ./.docker/web.DockerFile
    environment:
      PORT: ${WEB_PORT}
      REACT_APP_ENV: ${ENV}
      REACT_APP_FIREBASE_CLIENT_CONFIG: ${REACT_APP_FIREBASE_CLIENT_CONFIG}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ./front_end:/app
    command: >
      bash -c "npm install && npm run start"
    networks:
      - api-network

    

networks:
  api-network:
     driver: bridge
