on:
  push:
    branches:
      - master

jobs:
  release-prod:
    name: Deploy production to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2.pem
          chmod 400 ec2.pem
      
      - name: Connnect to EC2
        run: |
          ssh -i "ec2.pem" -o StrictHostKeyChecking=no ${{ secrets.EC2_CONNECTION }}
      
      - name: Pull code from Github
        run: |
          cd cd /home/ec2-user/EC2-RDS-S3-tutorial
          git pull origin master
          make stop
          make clean
          make build
          make prod
      
      - name: Exit And Remove SSH Key
        run: |
          exit
          rm ec2.pem